services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DOMAIN_ADMIN}
      POSTGRES_PASSWORD: ${DOMAIN_ADMIN_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  django:
    build:
      context: ./django
    container_name: django
    environment:
      DJANGO_PORT: ${DJANGO_PORT}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DJANGO_WSGI_MODULE: ${DJANGO_WSGI_MODULE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DOMAIN_ADMIN}
      POSTGRES_PASSWORD: ${DOMAIN_ADMIN_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: postgres://${DOMAIN_ADMIN}:${DOMAIN_ADMIN_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - postgres
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    environment:
      DOMAIN: ${DOMAIN}
      NGINX_HTTP_PORT: ${NGINX_HTTP_PORT}
      NGINX_HTTPS_PORT: ${NGINX_HTTPS_PORT}
      CERTBOT_EMAIL: ${DOMAIN_ADMIN_EMAIL}
      CERTBOT_DOMAIN: ${DOMAIN}
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - certbot

  certbot:
    build:
      context: ./certbot
    container_name: certbot
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $!; done'"

volumes:
  postgres_data:
  letsencrypt:

networks:
  backend:
  frontend:
